import { Helmet } from 'react-helmet-async';
import { MapPin, Phone } from 'lucide-react';
import { useState } from 'react';
import AnimatedSection from '@/components/AnimatedSection/AnimatedSection';
import HeroBanner from '@/components/HeroBanner/HeroBanner';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Section, Eyebrow } from '@/components/ui/section';
import { SITE } from '@/lib/site';
import {
  graph,
  webPage,
  breadcrumb,
  offerCatalog,
  service,
} from '@/lib/schema';

const DOMAIN = SITE.domain;

const contactJsonLd = graph([
  webPage({ id: 'webpage', url: '/contact', name: 'Contact Palmetto Consulting of Columbia', type: 'ContactPage' }),
  offerCatalog('Insurance Consulting Services', [
    service({ name: 'Captive Insurance Company Design' }),
    service({ name: 'Captive Growth Management' }),
    service({ name: 'Insurance CFO Services', serviceType: 'Insurance CFO Services', category: 'Insurance Consulting' }),
    service({ name: 'Insurance Controllership', serviceType: 'Insurance Controllership', category: 'Insurance Consulting' }),
  ]),
  breadcrumb([
    { name: 'Home', path: '/' },
    { name: 'Contact Us', path: '/contact' },
  ]),
]);

export default function Contact() {
  const [form, setForm] = useState({ name: '', email: '', message: '' });
  const [submitting, setSubmitting] = useState(false);

  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    const { toast } = await import('sonner');
    try {
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || 'Failed to send message. Please try again.');
      toast.success('Message sent. We will be in touch soon.');
      setForm({ name: '', email: '', message: '' });
    } catch (err) {
      toast.error(err.message || 'Something went wrong. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      <Helmet>
        <title>Contact Us | Palmetto Consulting of Columbia | Columbia, SC</title>
        <meta name="description" content="Contact Palmetto Consulting of Columbia, LLC. Reach our independent insurance consulting team in Columbia, SC at 803-904-8461. All business is generated by referral, we'd love to hear from you." />
        <meta name="robots" content="index, follow, max-image-preview:large" />
        <link rel="canonical" href={`${DOMAIN}/contact`} />
        <meta property="og:url" content={`${DOMAIN}/contact`} />
        <meta property="og:title" content="Contact Us | Palmetto Consulting of Columbia" />
        <meta property="og:description" content="Reach Palmetto Consulting of Columbia at our Columbia, SC office. Independent insurance consultants available by phone at 803-904-8461." />
        <meta name="twitter:title" content="Contact Us | Palmetto Consulting of Columbia" />
        <meta name="twitter:description" content="Contact Palmetto Consulting of Columbia, independent insurance consultants in Columbia, SC. Call 803-904-8461 or send us a message." />
        <script type="application/ld+json">{JSON.stringify(contactJsonLd)}</script>
      </Helmet>

      <HeroBanner image="/hero-contact.webp" eyebrow="Reach Out" heading="Contact Us" />

      <Section>
        <div className="grid gap-12 lg:grid-cols-2 lg:gap-16">
          <AnimatedSection>
            <Eyebrow>Get in Touch</Eyebrow>
            <h2 className="mb-6 text-3xl md:text-4xl font-extrabold tracking-tight text-[var(--color-navy)]">
              We&apos;d love to hear from you
            </h2>
            <p className="mb-5 text-base leading-7 text-[var(--color-muted)]" data-speakable>
              All of our business is generated by referral. If you&apos;ve been referred to us or are
              interested in learning how Palmetto can help your organization, please reach out, we&apos;re
              happy to have a conversation at no obligation.
            </p>
            <p className="mb-8 text-base leading-7 text-[var(--color-muted)]">
              Our team of independent insurance consultants is based in Columbia, South Carolina and
              serves clients across the United States. Whether you&apos;re exploring captive insurance for
              the first time or need experienced CFO-level guidance for an established carrier, we&apos;re
              here to help.
            </p>

            <ul className="space-y-5">
              <li className="flex gap-4">
                <span className="flex size-12 shrink-0 items-center justify-center rounded-sm bg-[var(--color-bg)] text-[var(--color-teal)]">
                  <MapPin size={24} aria-hidden="true" />
                </span>
                <div className="text-sm leading-7 text-[var(--color-ink)]">
                  <p className="text-xs font-bold uppercase tracking-[0.12em] text-[var(--color-muted)]">Office Address</p>
                  <p>1325 Park St. Suite 200</p>
                  <p>Columbia, SC 29201</p>
                </div>
              </li>
              <li className="flex gap-4">
                <span className="flex size-12 shrink-0 items-center justify-center rounded-sm bg-[var(--color-bg)] text-[var(--color-teal)]">
                  <Phone size={24} aria-hidden="true" />
                </span>
                <div className="text-sm leading-7">
                  <p className="text-xs font-bold uppercase tracking-[0.12em] text-[var(--color-muted)]">Phone</p>
                  <a
                    href="tel:+18039048461"
                    className="text-lg font-bold text-[var(--color-navy)] hover:text-[var(--color-teal)]"
                  >
                    803-904-8461
                  </a>
                </div>
              </li>
            </ul>
          </AnimatedSection>

          <AnimatedSection delay={150}>
            <Card>
              <CardContent className="p-8">
                <form onSubmit={handleSubmit} noValidate className="space-y-5">
                  <div className="space-y-2">
                    <Label htmlFor="name">Full Name</Label>
                    <Input
                      id="name"
                      name="name"
                      type="text"
                      value={form.name}
                      onChange={handleChange}
                      placeholder="John Smith"
                      required
                      autoComplete="name"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email Address</Label>
                    <Input
                      id="email"
                      name="email"
                      type="email"
                      value={form.email}
                      onChange={handleChange}
                      placeholder="john@example.com"
                      required
                      autoComplete="email"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="message">Message</Label>
                    <Textarea
                      id="message"
                      name="message"
                      rows={6}
                      value={form.message}
                      onChange={handleChange}
                      placeholder="Tell us how we can help..."
                      required
                    />
                  </div>
                  <Button type="submit" disabled={submitting} className="w-full">
                    {submitting ? 'Sending…' : 'Send Message'}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </AnimatedSection>
        </div>
      </Section>
    </>
  );
}
