import { Helmet } from 'react-helmet-async';
import { CheckCircle, MapPin, Phone } from '@phosphor-icons/react';
import { useState } from 'react';
import AnimatedSection from '../../components/AnimatedSection/AnimatedSection';
import styles from './Contact.module.css';

const DOMAIN = 'https://yourdomain.com';

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home',       item: `${DOMAIN}/` },
    { '@type': 'ListItem', position: 2, name: 'Contact Us', item: `${DOMAIN}/contact` },
  ],
};

export default function Contact() {
  const [form, setForm] = useState({ name: '', email: '', message: '' });
  const [submitted, setSubmitted] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setSubmitted(true);
    setForm({ name: '', email: '', message: '' });
  };

  return (
    <>
      <Helmet>
        <title>Contact Us | Palmetto Consulting of Columbia — Columbia, SC</title>
        <meta name="description" content="Contact Palmetto Consulting of Columbia, LLC. Reach our independent insurance consulting team in Columbia, SC at 803-904-8461. All business is generated by referral — we'd love to hear from you." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href={`${DOMAIN}/contact`} />

        {/* Open Graph */}
        <meta property="og:type"        content="website" />
        <meta property="og:url"         content={`${DOMAIN}/contact`} />
        <meta property="og:title"       content="Contact Us | Palmetto Consulting of Columbia" />
        <meta property="og:description" content="Reach Palmetto Consulting of Columbia at our Columbia, SC office. Independent insurance consultants available by phone at 803-904-8461." />
        <meta property="og:image"       content="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80" />
        <meta property="og:site_name"   content="Palmetto Consulting of Columbia" />

        {/* Twitter Card */}
        <meta name="twitter:card"        content="summary_large_image" />
        <meta name="twitter:title"       content="Contact Us | Palmetto Consulting of Columbia" />
        <meta name="twitter:description" content="Contact Palmetto Consulting of Columbia — independent insurance consultants in Columbia, SC. Call 803-904-8461 or send us a message." />
        <meta name="twitter:image"       content="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80" />

        {/* BreadcrumbList Schema */}
        <script type="application/ld+json">
          {JSON.stringify(breadcrumbSchema)}
        </script>
      </Helmet>

      <section className={styles.banner}>
        <div className={styles.bannerOverlay} />
        <div className={`container ${styles.bannerContent}`}>
          <AnimatedSection>
            <p className={styles.bannerEyebrow}>Reach Out</p>
            <h1 className={styles.bannerHeading}>Contact Us</h1>
          </AnimatedSection>
        </div>
      </section>

      <section className={`section ${styles.contactSection}`}>
        <div className="container">
          <div className={styles.grid}>
            <AnimatedSection className={styles.info}>
              <p className={styles.eyebrow}>Get in Touch</p>
              <h2 className={styles.infoHeading}>We&apos;d love to hear from you</h2>
              <p className={styles.infoText}>
                All of our business is generated by referral. If you&apos;ve been referred to us or are
                interested in learning how Palmetto can help your organization, please reach out — we&apos;re
                happy to have a conversation at no obligation.
              </p>
              <p className={styles.infoText}>
                Our team of independent insurance consultants is based in Columbia, South Carolina and
                serves clients across the United States. Whether you&apos;re exploring captive insurance for
                the first time or need experienced CFO-level guidance for an established carrier, we&apos;re
                here to help.
              </p>
              <div className={styles.details}>
                <div className={styles.detail}>
                  <span className={styles.detailIcon}>
                    <MapPin size={24} weight="duotone" aria-hidden="true" />
                  </span>
                  <div>
                    <p className={styles.detailLabel}>Office Address</p>
                    <p>1325 Park St. Suite 200</p>
                    <p>Columbia, SC 29201</p>
                  </div>
                </div>
                <div className={styles.detail}>
                  <span className={styles.detailIcon}>
                    <Phone size={24} weight="duotone" aria-hidden="true" />
                  </span>
                  <div>
                    <p className={styles.detailLabel}>Phone</p>
                    <a href="tel:8039048461" className={styles.phone}>803-904-8461</a>
                  </div>
                </div>
              </div>
            </AnimatedSection>

            <AnimatedSection delay={150}>
              {submitted ? (
                <div className={styles.success}>
                  <div className={styles.successIcon}>
                    <CheckCircle size={30} weight="fill" aria-hidden="true" />
                  </div>
                  <h3>Thank you for reaching out!</h3>
                  <p>We&apos;ll be in touch with you soon.</p>
                  <button className={styles.resetBtn} onClick={() => setSubmitted(false)}>
                    Send another message
                  </button>
                </div>
              ) : (
                <form className={styles.form} onSubmit={handleSubmit} noValidate>
                  <div className={styles.field}>
                    <label htmlFor="name">Full Name</label>
                    <input
                      id="name"
                      type="text"
                      name="name"
                      value={form.name}
                      onChange={handleChange}
                      placeholder="John Smith"
                      required
                    />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="email">Email Address</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      value={form.email}
                      onChange={handleChange}
                      placeholder="john@example.com"
                      required
                    />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="message">Message</label>
                    <textarea
                      id="message"
                      name="message"
                      rows={6}
                      value={form.message}
                      onChange={handleChange}
                      placeholder="Tell us how we can help..."
                      required
                    />
                  </div>
                  <button type="submit" className={styles.submitBtn}>
                    Send Message
                  </button>
                </form>
              )}
            </AnimatedSection>
          </div>
        </div>
      </section>
    </>
  );
}
