import { useState } from 'react';
import AnimatedSection from '../../components/AnimatedSection/AnimatedSection';
import styles from './Contact.module.css';

export default function Contact() {
  const [form, setForm] = useState({ name: '', email: '', message: '' });
  const [submitted, setSubmitted] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setSubmitted(true);
    setForm({ name: '', email: '', message: '' });
  };

  return (
    <>
      {/* Banner */}
      <section className={styles.banner}>
        <div className={styles.bannerOverlay} />
        <div className={`container ${styles.bannerContent}`}>
          <AnimatedSection>
            <p className={styles.bannerEyebrow}>Reach Out</p>
            <h1 className={styles.bannerHeading}>Contact Us</h1>
          </AnimatedSection>
        </div>
      </section>

      {/* Contact Body */}
      <section className={`section ${styles.contactSection}`}>
        <div className="container">
          <div className={styles.grid}>

            {/* Info */}
            <AnimatedSection className={styles.info}>
              <p className={styles.eyebrow}>Get in Touch</p>
              <h2 className={styles.infoHeading}>We'd love to hear from you</h2>
              <p className={styles.infoText}>
                All of our business is generated by referral. If you've been referred to us or are
                interested in learning how Palmetto can help your organization, please reach out.
              </p>
              <div className={styles.details}>
                <div className={styles.detail}>
                  <span className={styles.detailIcon}>📍</span>
                  <div>
                    <p className={styles.detailLabel}>Office Address</p>
                    <p>1325 Park St. Suite 200</p>
                    <p>Columbia, SC 29201</p>
                  </div>
                </div>
                <div className={styles.detail}>
                  <span className={styles.detailIcon}>📞</span>
                  <div>
                    <p className={styles.detailLabel}>Phone</p>
                    <a href="tel:8039048461" className={styles.phone}>803-904-8461</a>
                  </div>
                </div>
              </div>
            </AnimatedSection>

            {/* Form */}
            <AnimatedSection delay={150}>
              {submitted ? (
                <div className={styles.success}>
                  <div className={styles.successIcon}>✓</div>
                  <h3>Thank you for reaching out!</h3>
                  <p>We'll be in touch with you soon.</p>
                  <button className={styles.resetBtn} onClick={() => setSubmitted(false)}>
                    Send another message
                  </button>
                </div>
              ) : (
                <form className={styles.form} onSubmit={handleSubmit} noValidate>
                  <div className={styles.field}>
                    <label htmlFor="name">Full Name</label>
                    <input
                      id="name"
                      type="text"
                      name="name"
                      value={form.name}
                      onChange={handleChange}
                      placeholder="John Smith"
                      required
                    />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="email">Email Address</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      value={form.email}
                      onChange={handleChange}
                      placeholder="john@example.com"
                      required
                    />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="message">Message</label>
                    <textarea
                      id="message"
                      name="message"
                      rows={6}
                      value={form.message}
                      onChange={handleChange}
                      placeholder="Tell us how we can help..."
                      required
                    />
                  </div>
                  <button type="submit" className={styles.submitBtn}>
                    Send Message
                  </button>
                </form>
              )}
            </AnimatedSection>
          </div>
        </div>
      </section>
    </>
  );
}
