import { Helmet } from 'react-helmet-async';
import { Buildings, ChartLineUp, Handshake, Target } from '@phosphor-icons/react';
import { Link } from 'react-router-dom';
import AnimatedSection from '@/components/AnimatedSection/AnimatedSection';
import StatsBar from '@/components/StatsBar/StatsBar';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Section, Eyebrow, SectionHeading } from '@/components/ui/section';
import { SITE } from '@/lib/site';

const DOMAIN = SITE.domain;
const OG_IMAGE = SITE.ogImage;

const services = [
  {
    icon: Buildings,
    title: 'Insurance Company Design & Structure',
    body: 'Whether you need a captive to insure your commercially un-insurable risks, are an agency seeking a reinsurance vehicle, or want to build a new commercial carrier from the ground up, we can help.',
  },
  {
    icon: Handshake,
    title: 'Industry Relationships',
    body: "Does your carrier need additional products or distribution alternatives to your current agency force? Our deep ties to the insurance community and relationships with MGAs, other carriers, and service providers allow us to bring our clients solutions to the problems that we can't solve ourselves.",
  },
  {
    icon: ChartLineUp,
    title: 'Growth Management',
    body: 'Even for profitable insurance companies, growth can present a host of challenges and complexities. We can assist with reinsurance structure, rating agency relationships, and the regulatory challenges that rapid growth can bring.',
  },
  {
    icon: Target,
    title: 'Deliberately Not "One-Size Fits All"',
    body: 'Unlike large firms, we are not beholden to outside ownership, Wall Street, or sales targets. We are relationship-builders as much as we are insurance-company-builders. Sometimes the right solution is to do nothing at all, and we are always okay with that.',
  },
];

const faqs = [
  { q: 'What is a captive insurance company?', a: 'A captive insurance company is a wholly-owned subsidiary insurer that provides risk-mitigation services to its parent or related entities. Captives can insure risks that are uneconomical or unavailable in the traditional commercial market and can return underwriting profit and investment income to the owner.' },
  { q: 'Who should consider forming a captive insurance company?', a: "Mid-market and larger companies with predictable, financeable risks, agencies seeking a reinsurance vehicle, and groups of similar businesses pooling exposures are common candidates. The right fit depends on risk profile, premium volume, regulatory tolerance, and a long-term commitment to disciplined underwriting." },
  { q: 'What types of captives does PCC work with?', a: 'We advise on pure (single-parent) captives, group captives, association captives, agency-owned reinsurance vehicles, and traditional commercial carriers. We are domicile-agnostic and select the structure and jurisdiction that best fits the client.' },
  { q: 'What does a fractional insurance CFO do?', a: 'A fractional insurance CFO provides treasury, investment monitoring, tax planning, budget analysis, reinsurance negotiation, rating-agency relationship management, and internal audit oversight, without the overhead of a full-time executive. This is well-suited to early-stage carriers and growing captives.' },
  { q: 'What services does Palmetto Consulting of Columbia provide?', a: 'PCC provides captive insurance company design and structure, full Chief Financial Officer (CFO) services, controllership services, growth management, reinsurance structuring, rating-agency relationship management, and regulatory navigation for both captive and traditional insurance companies.' },
  { q: 'Where is Palmetto Consulting of Columbia located?', a: 'Our office is at 1325 Park St. Suite 200, Columbia, SC 29201. We serve clients across the United States.' },
  { q: 'How do I engage Palmetto Consulting?', a: "All of our business is generated by referral. If you've been referred or are interested in learning how PCC can help your organization, please call 803-904-8461 or use our contact form. Initial conversations are at no obligation." },
  { q: 'How long has Palmetto Consulting been in business?', a: 'Palmetto Consulting of Columbia, LLC was founded in 1998 by John A. Weitzel after a nearly 50-year career in the insurance industry, primarily as a Chief Financial Officer.' },
];

const homeJsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebSite',
      '@id': `${DOMAIN}/#website`,
      url: DOMAIN,
      name: 'Palmetto Consulting of Columbia',
      publisher: { '@id': `${DOMAIN}/#organization` },
      inLanguage: 'en-US',
    },
    {
      '@type': 'WebPage',
      '@id': `${DOMAIN}/#webpage`,
      url: `${DOMAIN}/`,
      name: 'Palmetto Consulting of Columbia | Captive Insurance Consultants',
      isPartOf: { '@id': `${DOMAIN}/#website` },
      about: { '@id': `${DOMAIN}/#organization` },
      inLanguage: 'en-US',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['h1', 'h2', '[data-speakable]'] },
    },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: `${DOMAIN}/` }] },
    {
      '@type': 'OfferCatalog',
      name: 'Insurance Consulting Services',
      itemListElement: services.map((s, i) => ({
        '@type': 'Offer',
        position: i + 1,
        itemOffered: {
          '@type': 'Service',
          name: s.title,
          description: s.body,
          provider: { '@id': `${DOMAIN}/#organization` },
          areaServed: { '@type': 'Country', name: 'United States' },
          serviceType: 'Insurance Consulting',
          category: 'Captive Insurance',
          additionalType: 'https://en.wikipedia.org/wiki/Captive_insurance',
        },
      })),
    },
    {
      '@type': 'FAQPage',
      mainEntity: faqs.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    },
  ],
};

export default function Home() {
  return (
    <>
      <Helmet>
        <title>Palmetto Consulting of Columbia | Captive Insurance Consultants in Columbia, SC</title>
        <meta name="description" content="Palmetto Consulting of Columbia, LLC are independent insurance consultants in Columbia, SC specializing in captive insurance design, growth management, and CFO services since 1998." />
        <meta name="robots" content="index, follow, max-image-preview:large" />
        <link rel="canonical" href={`${DOMAIN}/`} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={`${DOMAIN}/`} />
        <meta property="og:title" content="Palmetto Consulting of Columbia | Captive Insurance Consultants" />
        <meta property="og:description" content="Independent insurance consultants in Columbia, SC focused on captive insurance and the traditional insurance marketplace. Serving clients since 1998." />
        <meta property="og:image" content={OG_IMAGE} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:site_name" content="Palmetto Consulting of Columbia" />
        <meta property="og:locale" content="en_US" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Palmetto Consulting of Columbia | Captive Insurance Consultants" />
        <meta name="twitter:description" content="Independent insurance consultants in Columbia, SC focused on captive insurance and the traditional insurance marketplace since 1998." />
        <meta name="twitter:image" content={OG_IMAGE} />
        <script type="application/ld+json">{JSON.stringify(homeJsonLd)}</script>
      </Helmet>

      {/* Hero */}
      <section
        className="relative isolate flex min-h-[78vh] items-center text-white"
        style={{
          backgroundImage:
            "linear-gradient(rgba(0,48,87,0.55), rgba(0,48,87,0.78)), url('/hero-buildings.webp')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <div className="container-x relative z-10 max-w-3xl">
          <p className="mb-3 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-cyan)] animate-fade-up">
            Independent Insurance Consultants in Columbia, SC
          </p>
          <h1 className="mb-6 text-4xl md:text-6xl font-extrabold leading-[1.05] tracking-tight animate-fade-up">
            Palmetto Consulting<br />of Columbia
          </h1>
          <p className="mb-10 text-lg md:text-xl text-white/85 animate-fade-up" data-speakable>
            Focused on the intersection of captive insurance<br className="hidden md:inline" />
            {' '}and the traditional insurance marketplace.
          </p>
          <Button asChild size="lg" className="animate-fade-up">
            <Link to="/contact">Let&apos;s Work Together</Link>
          </Button>
        </div>
      </section>

      <StatsBar />

      {/* Mission */}
      <Section>
        <AnimatedSection className="mx-auto max-w-3xl text-center">
          <p className="text-lg md:text-xl leading-8 text-[var(--color-navy)]" data-speakable>
            Based in Columbia, South Carolina, Palmetto remains uniquely focused on the intersection
            of captive insurance and the traditional insurance marketplace, primarily on those
            opportunities where our backgrounds can add the most value to our clients and partners.
          </p>
        </AnimatedSection>
      </Section>

      {/* Services */}
      <Section className="bg-white border-y border-[var(--color-border-soft)]">
        <AnimatedSection className="text-center">
          <Eyebrow>What We Do</Eyebrow>
          <SectionHeading>Our Services</SectionHeading>
        </AnimatedSection>
        <div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-2">
          {services.map((s, i) => {
            const Icon = s.icon;
            return (
              <AnimatedSection key={s.title} delay={i * 90}>
                <Card className="h-full">
                  <CardContent className="flex h-full flex-col p-8">
                    <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-sm bg-[var(--color-bg)] text-[var(--color-teal)]">
                      <Icon size={28} weight="duotone" aria-hidden="true" />
                    </div>
                    <h3 className="mb-3 text-lg font-bold text-[var(--color-navy)]">{s.title}</h3>
                    <p className="text-sm leading-7 text-[var(--color-muted)]">{s.body}</p>
                  </CardContent>
                </Card>
              </AnimatedSection>
            );
          })}
        </div>
      </Section>

      {/* CTA */}
      <section className="bg-[var(--color-navy)] py-20 text-center text-white">
        <div className="container-x">
          <AnimatedSection>
            <h2 className="mb-8 text-2xl md:text-4xl font-extrabold leading-tight tracking-tight">
              Your goals are individual.<br />
              We believe captive insurance should be too.
            </h2>
            <Button asChild variant="outline" size="lg">
              <Link to="/contact">Take the Next Step</Link>
            </Button>
          </AnimatedSection>
        </div>
      </section>
    </>
  );
}
