import { useEffect, useRef } from 'react';
import { Helmet } from 'react-helmet-async';
import { gsap } from 'gsap';
import { Buildings, ChartLineUp, Handshake, Target } from '@phosphor-icons/react';
import CTAButton from '../../components/CTAButton/CTAButton';
import ServiceCard from '../../components/ServiceCard/ServiceCard';
import AnimatedSection from '../../components/AnimatedSection/AnimatedSection';
import StatsBar from '../../components/StatsBar/StatsBar';
import styles from './Home.module.css';

const DOMAIN = 'https://palmettoconsulting.us';
const OG_IMAGE = `${DOMAIN}/og.png`;

const services = [
  {
    icon: <Buildings size={32} weight="duotone" aria-hidden="true" />,
    title: 'Insurance Company Design & Structure',
    body: 'Whether you need a captive to insure your commercially un-insurable risks, are an agency seeking a reinsurance vehicle, or want to build a new commercial carrier from the ground up - we can help.',
  },
  {
    icon: <Handshake size={32} weight="duotone" aria-hidden="true" />,
    title: 'Industry Relationships',
    body: "Does your carrier need additional products or distribution alternatives to your current agency force? Our deep ties to the insurance community and relationships with MGAs, other carriers, and service providers allow us to bring our clients solutions to the problems that we can't solve ourselves.",
  },
  {
    icon: <ChartLineUp size={32} weight="duotone" aria-hidden="true" />,
    title: 'Growth Management',
    body: 'Even for profitable insurance companies, growth can present a host of challenges and complexities. We can assist with reinsurance structure, rating agency relationships, and the regulatory challenges that rapid growth can bring.',
  },
  {
    icon: <Target size={32} weight="duotone" aria-hidden="true" />,
    title: 'Deliberately Not "One-Size Fits All"',
    body: 'Unlike large firms, we are not beholden to outside ownership, Wall Street, or sales targets. We are relationship-builders as much as we are insurance-company-builders. Sometimes the right solution is to do nothing at all - and we are always okay with that.',
  },
];

const faqs = [
  {
    q: 'What is a captive insurance company?',
    a: 'A captive insurance company is a wholly-owned subsidiary insurer that provides risk-mitigation services to its parent or related entities. Captives can insure risks that are uneconomical or unavailable in the traditional commercial market and can return underwriting profit and investment income to the owner.',
  },
  {
    q: 'What services does Palmetto Consulting of Columbia provide?',
    a: 'PCC provides captive insurance company design and structure, full Chief Financial Officer (CFO) services, controllership services, growth management, reinsurance structuring, rating-agency relationship management, and regulatory navigation for both captive and traditional insurance companies.',
  },
  {
    q: 'Where is Palmetto Consulting of Columbia located?',
    a: 'Our office is at 1325 Park St. Suite 200, Columbia, SC 29201. We serve clients across the United States.',
  },
  {
    q: 'How do I engage Palmetto Consulting?',
    a: "All of our business is generated by referral. If you've been referred or are interested in learning how PCC can help your organization, please call 803-904-8461 or use our contact form. Initial conversations are at no obligation.",
  },
  {
    q: 'How long has Palmetto Consulting been in business?',
    a: 'Palmetto Consulting of Columbia, LLC was founded in 1998 by John A. Weitzel after a nearly 50-year career in the insurance industry, primarily as a Chief Financial Officer.',
  },
];

const homeJsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebPage',
      '@id': `${DOMAIN}/#webpage`,
      url: `${DOMAIN}/`,
      name: 'Palmetto Consulting of Columbia | Captive Insurance Consultants',
      isPartOf: { '@id': `${DOMAIN}/#website` },
      about: { '@id': `${DOMAIN}/#organization` },
      inLanguage: 'en-US',
      speakable: {
        '@type': 'SpeakableSpecification',
        cssSelector: ['h1', 'h2', '[data-speakable]'],
      },
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${DOMAIN}/` },
      ],
    },
    {
      '@type': 'OfferCatalog',
      name: 'Insurance Consulting Services',
      itemListElement: services.map((s, i) => ({
        '@type': 'Offer',
        position: i + 1,
        itemOffered: {
          '@type': 'Service',
          name: s.title,
          description: s.body,
          provider: { '@id': `${DOMAIN}/#organization` },
          areaServed: { '@type': 'Country', name: 'United States' },
          serviceType: 'Insurance Consulting',
          category: 'Captive Insurance',
        },
      })),
    },
    {
      '@type': 'FAQPage',
      mainEntity: faqs.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    },
  ],
};

export default function Home() {
  const heroContentRef = useRef(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.from('[data-hero-el]', {
        autoAlpha: 0,
        y: 22,
        duration: 0.75,
        stagger: 0.16,
        ease: 'power2.out',
        delay: 0.2,
      });
    }, heroContentRef);
    return () => ctx.revert();
  }, []);

  return (
    <>
      <Helmet>
        <title>Palmetto Consulting of Columbia | Captive Insurance Consultants — Columbia, SC</title>
        <meta name="description" content="Palmetto Consulting of Columbia, LLC are independent insurance consultants in Columbia, SC specializing in captive insurance design, growth management, and CFO services since 1998." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href={`${DOMAIN}/`} />

        {/* Open Graph */}
        <meta property="og:type"        content="website" />
        <meta property="og:url"         content={`${DOMAIN}/`} />
        <meta property="og:title"       content="Palmetto Consulting of Columbia | Captive Insurance Consultants" />
        <meta property="og:description" content="Independent insurance consultants in Columbia, SC focused on captive insurance and the traditional insurance marketplace. Serving clients since 1998." />
        <meta property="og:image"       content={OG_IMAGE} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:site_name"   content="Palmetto Consulting of Columbia" />
        <meta property="og:locale"      content="en_US" />

        {/* Twitter Card */}
        <meta name="twitter:card"        content="summary_large_image" />
        <meta name="twitter:title"       content="Palmetto Consulting of Columbia | Captive Insurance Consultants" />
        <meta name="twitter:description" content="Independent insurance consultants in Columbia, SC focused on captive insurance and the traditional insurance marketplace since 1998." />
        <meta name="twitter:image"       content={OG_IMAGE} />

        <script type="application/ld+json">{JSON.stringify(homeJsonLd)}</script>
      </Helmet>

      <section className={styles.hero}>
        <div className={styles.heroOverlay} />
        <div className={`container ${styles.heroContent}`} ref={heroContentRef}>
          <p className={styles.heroEyebrow} data-hero-el="">
            Independent Insurance Consultants — Columbia, SC
          </p>
          <h1 className={styles.heroHeading} data-hero-el="">
            Palmetto Consulting<br />of Columbia
          </h1>
          <p className={styles.heroSub} data-hero-el="">
            Focused on the intersection of captive insurance<br />
            and the traditional insurance marketplace.
          </p>
          <div data-hero-el="">
            <CTAButton label="Let's Work Together" to="/contact" variant="primary" />
          </div>
        </div>
      </section>

      <StatsBar />

      <section className={`section ${styles.message}`}>
        <div className="container">
          <AnimatedSection>
            <div className={styles.messageInner}>
              <p className={styles.messageText}>
                Based in Columbia, South Carolina, Palmetto remains uniquely focused on the intersection
                of captive insurance and the traditional insurance marketplace — primarily on those
                opportunities where our backgrounds can add the most value to our clients and partners.
              </p>
            </div>
          </AnimatedSection>
        </div>
      </section>

      <section className={`section ${styles.services}`}>
        <div className="container">
          <AnimatedSection>
            <p className={styles.servicesEyebrow}>What We Do</p>
            <h2 className={styles.servicesHeading}>Our Services</h2>
          </AnimatedSection>
          <div className={styles.grid}>
            {services.map((s, i) => (
              <AnimatedSection key={s.title} delay={i * 100}>
                <ServiceCard title={s.title} body={s.body} icon={s.icon} />
              </AnimatedSection>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.cta}>
        <div className="container">
          <AnimatedSection>
            <h2 className={styles.ctaHeading}>
              Your goals are individual.<br />We believe captive insurance should be too.
            </h2>
            <CTAButton label="Take the Next Step" to="/contact" variant="outline" />
          </AnimatedSection>
        </div>
      </section>
    </>
  );
}
